version: '3.8'

services:
  koa-api:
    build: .
    container_name: anas-practice-nodejs-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start